"""
Project Constants

This module defines constants used throughout the fuzzing framework,
including default paths, file names, and configuration values.
"""

import os

# Default paths
DEFAULT_API_SOURCE_PATH = "./api_sources"
DEFAULT_API_DOCS_PATH = os.path.join(DEFAULT_API_SOURCE_PATH, "api_docs")
DEFAULT_API_CODES_PATH = os.path.join(DEFAULT_API_SOURCE_PATH, "api_codes")
DEFAULT_FUZZING_CASES_PATH = "./fuzzing_cases"
DEFAULT_LOGS_PATH = "./logs"
DEFAULT_VECTORSTORE_PATH = "./vectorstore"

# Default file names
DEFAULT_LOG_FILE_ST = "fuzz_log_st"
DEFAULT_LOG_FILE_APP = "fuzz_log_app"

# Default network configuration
DEFAULT_HUB_IP = "192.168.1.199"
DEFAULT_FUZZ_IP = "192.168.1.172"
DEFAULT_FUZZ_PORT = "34567"

# Default LLM models
DEFAULT_GPT_MODEL = "gpt-4o"
DEFAULT_CLAUDE_MODEL = "claude-3-7-sonnet-20250219"
DEFAULT_HUGGINGFACE_MODEL = "Qwen/Qwen2.5-Coder-32B-Instruct"

# Fuzzing parameters
DEFAULT_ROUND = "0"
DEFAULT_TOTAL_ROUNDS = "10"
DEFAULT_MAX_TOKENS = 16000
DEFAULT_TEMPERATURE = 0.1

# Log markers for extraction
LOG_START_MARKER = "testing code generated by gpt..."
LOG_END_MARKER = "test finished"
LOG_CONNECTION_MARKER = "connecting... connected"

# HTTP/Network constants
HTTP_CONTENT_TYPE_JSON = "application/json"
HTTP_OK = "200 OK"
HTTP_BAD_REQUEST = "400 Bad Request"
SOCKET_BUFFER_SIZE = 1024
SOCKET_RESPONSE_BUFFER_SIZE = 4096

# File extensions
EXT_JSON = ".json"
EXT_LUA = ".lua"
EXT_TXT = ".txt"
EXT_MD = ".md"
EXT_HTML = ".html"
EXT_JSONL = ".jsonl"
EXT_LOG = ".log"

# API key environment variables
ENV_OPENAI_API_KEY = "OPENAI_API_KEY"
ENV_ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY"
ENV_HUGGINGFACE_TOKEN = "HUGGINGFACE_TOKEN"

