"""
Case Extractor Module

This module provides utilities for extracting fuzzing test cases from
JSON files and organizing them by API and function.
"""

import os
import json
from typing import List, Dict
from config.api_config import FUZZING_API_CHOICES, FUNC_SUM


def extract_code_snippets(
    input_folder: str,
    output_base_folder: str = "deeper/round1"
) -> None:
    """
    Extract code snippets from JSON test case files and organize by API/function.
    
    This function reads test case JSON files, extracts code snippets, and
    writes them to text files organized by API and function name.
    
    Args:
        input_folder: Folder containing JSON test case files
        output_base_folder: Base folder for output text files
    """
    # Ensure the output base directory exists
    os.makedirs(output_base_folder, exist_ok=True)

    # Iterate through each API in fuzzing_api_choices
    for api_name in FUZZING_API_CHOICES:
        funcs = FUNC_SUM.get(api_name, [])

        # Ensure the API-specific output directory exists
        api_output_folder = os.path.join(output_base_folder, api_name)
        os.makedirs(api_output_folder, exist_ok=True)

        # Iterate through each function in the API
        for func in funcs:
            collected_snippets = []  # List to store extracted code snippets

            # Iterate through all possible JSON files (num from 0 to 9)
            for num in range(10):
                json_filename = f"{api_name}-{num}{func}.json"
                json_filepath = os.path.join(input_folder, json_filename)

                # Check if the JSON file exists
                if os.path.exists(json_filepath):
                    # Read and parse the JSON file
                    with open(json_filepath, "r", encoding="utf-8") as json_file:
                        try:
                            test_cases = json.load(json_file)
                            # Extract code snippets
                            for case in test_cases:
                                if "Code_Snippets" in case:
                                    collected_snippets.extend(case["Code_Snippets"])
                        except json.JSONDecodeError:
                            print(f"Error decoding JSON in file: {json_filepath}")

            # Write the extracted code snippets to the corresponding text file
            if collected_snippets:
                output_filepath = os.path.join(api_output_folder, f"{func}.txt")
                with open(output_filepath, "w", encoding="utf-8") as txt_file:
                    txt_file.write("\n".join(collected_snippets))

                print(f"Extracted {len(collected_snippets)} lines to {output_filepath}")


def extract_log_content(
    directory: str,
    start_marker: str = "testing code generated by gpt...",
    end_marker: str = "test finished"
) -> None:
    """
    Extract log content between markers and overwrite log files.
    
    This function processes log files and extracts only the content
    between specified start and end markers.
    
    Args:
        directory: Directory containing log files
        start_marker: Marker indicating start of relevant content
        end_marker: Marker indicating end of relevant content
    """
    for root, _, files in os.walk(directory):
        for filename in files:
            if filename.endswith('.log'):
                file_path = os.path.join(root, filename)
                
                with open(file_path, 'r') as file:
                    lines = file.readlines()
                
                extracting = False
                extracted_lines = []
                
                for line in lines:
                    if start_marker in line:
                        extracting = True
                        continue
                    if end_marker in line:
                        extracting = False
                        continue
                    if extracting:
                        extracted_lines.append(line)
                
                # Overwrite file with extracted content
                with open(file_path, 'w') as file:
                    file.writelines(extracted_lines)
                
                print(f"Extracted content from {file_path}")

